class EnthusiastData {
  static List<Map<String, dynamic>> plantData = [
    {
      "name": "Apple Gourd",
      "north_growing_season": ["Feb-Mar", "Jun-Jul"],
      "south_growing_season": ["Feb-Mar", "Jun-Jul"	],
      "germination_temp": "20-30",
      "sowing_method": "Direct",
      "sowing_depth": "1",
      "sowing_distance_between_seeds": "12",
      "sowing_distance_between_rows": "12",
      "days_to_maturation": "70-80",
      "link": "https://www.allthatgrows.in/products/apple-gourd-tinda"
    },
    {
      "name": "Beetroot",
      "north_growing_season": ["Oct-Nov"],
      "south_growing_season": ["Aug-Nov"],
      "germination_temp": "10-30",
      "sowing_method": "Direct",
      "sowing_depth": "1",
      "sowing_distance_between_seeds": "4",
      "sowing_distance_between_rows": "18",
      "days_to_maturation": "80-90",
      "link": "https://www.allthatgrows.in/products/beet-root-ruby-red"
    },
    {
      "name": "Bitter Gourd",
      "north_growing_season": ["Feb-Mar", "Jun-Jul"],
      "south_growing_season": ["Nov-Dec", "Dec-Jan", "Jun-Jul"],
      "germination_temp": "20-30",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "1",
      "sowing_distance_between_rows": "4",
      "days_to_maturation": "55-60",
      "link": "https://www.allthatgrows.in/products/bitter-gourd"
    },
    {
      "name": "Bottle Gourd",
      "north_growing_season": ["Feb-Mar", "Jun-Jul"],
      "south_growing_season": ["Nov-Dec", "Dec-Jan", "Jun-Jul"],
      "germination_temp": "20-30",
      "sowing_method": "Direct",
      "sowing_depth": "1-2",
      "sowing_distance_between_seeds": "1",
      "sowing_distance_between_rows": "4",
      "days_to_maturation": "55-60",
      "link": "https://www.allthatgrows.in/products/bottle-gourd"
    },
    {
      "name": "Broccoli",
      "north_growing_season": ["Aug-Sept"],
      "south_growing_season": ["Aug-Sept"],
      "germination_temp": "21-23",
      "sowing_method": "Transplant",
      "sowing_depth": "1.5",
      "sowing_distance_between_seeds": "1",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "90-100",
      "link": "https://www.allthatgrows.in/products/broccoli"
    },
    {
      "name": "Cabbage",
      "north_growing_season": ["Sept-Oct"],
      "south_growing_season": ["Jun-Jul", "Oct-Nov"],
      "germination_temp": "10-20",
      "sowing_method": "Transplant",
      "sowing_depth": "0.25",
      "sowing_distance_between_seeds": "1",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "90-100",
      "link": "https://www.allthatgrows.in/products/cabbage-golden-acre"
    },
    {
      "name": "Capsicum",
      "north_growing_season": ["Nov-Jan", "May-Jun"],
      "south_growing_season": ["Jan-Feb", "May-Jun", "Oct-Nov"],
      "germination_temp": "15-25",
      "sowing_method": "Transplant",
      "sowing_depth": "0.25-0.5",
      "sowing_distance_between_seeds": "1.5",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "95-100",
      "link": "https://www.allthatgrows.in/products/capsicum-green"
    },
    {
      "name": "Carrot",
      "north_growing_season": ["Aug-Sept-Oct"],
      "south_growing_season": ["Aug-Nov"],
      "germination_temp": "10-30",
      "sowing_method": "Direct",
      "sowing_depth": "0.25",
      "sowing_distance_between_seeds": "2",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "75-80",
      "link": "https://www.allthatgrows.in/products/carrot-orange"
    },
    {
      "name": "Cucumber",
      "north_growing_season": ["Feb-Mar", "Jun", "Jul"],
      "south_growing_season": ["Jun-Jul", "Sept-Oct", "Dec-Jan"],
      "germination_temp": "16-32",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "NA",
      "sowing_distance_between_rows": "12",
      "days_to_maturation": "50-70",
      "link": "https://www.allthatgrows.in/products/cucumber"
    },
    {
      "name": "Beans",
      "north_growing_season": ["Feb-Mar"],
      "south_growing_season": ["NA"],
      "germination_temp": "16-30",
      "sowing_method": "Direct",
      "sowing_depth": "1-1.5",
      "sowing_distance_between_seeds": "8",
      "sowing_distance_between_rows": "18",
      "days_to_maturation": "45-50",
      "link": "https://www.allthatgrows.in/products/yellow-beans"
    },
    {
      "name": "Lettuce",
      "north_growing_season": ["Sept-Oct"],
      "south_growing_season": ["Oct-Dec"],
      "germination_temp": "7-27",
      "sowing_method": "Direct/Tranlsplant",
      "sowing_depth": "Surface Sow, cover lightly with soil",
      "sowing_distance_between_seeds": "NA",
      "sowing_distance_between_rows": "8-12",
      "days_to_maturation": "45-55",
      "link": "https://www.allthatgrows.in/products/lettuce-grand-rapids-seeds"
    },
    {
      "name": "Okra",
      "north_growing_season": ["Feb-Mar", "Jun-Jul"],
      "south_growing_season": ["Jan-Feb", "May-Jun", "Oct-Dec"],
      "germination_temp": "20-32",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "12",
      "sowing_distance_between_rows": "18",
      "days_to_maturation": "45-50",
      "link": "https://www.allthatgrows.in/products/okra-summer-beauty"
    },
    {
      "name": "Onion",
      "north_growing_season": ["May-Jun"],
      "south_growing_season": ["Mar-Apr", "May-Jun", "Sept-Oct"],
      "germination_temp": "10-32",
      "sowing_method": "Transplant",
      "sowing_depth": "0.25",
      "sowing_distance_between_seeds": "4",
      "sowing_distance_between_rows": "6",
      "days_to_maturation": "150-160",
      "link": "https://www.allthatgrows.in/products/onion-white"
    },
    {
      "name": "Peas",
      "north_growing_season": ["Sept-Oct-Nov"],
      "south_growing_season": ["Sept-Oct-Nov"],
      "germination_temp": "10-22",
      "sowing_method": "Direct",
      "sowing_depth": "1",
      "sowing_distance_between_seeds": "4",
      "sowing_distance_between_rows": "12",
      "days_to_maturation": "55-60",
      "link": "https://www.allthatgrows.in/products/peas"
    },
    {
      "name": "Radish",
      "north_growing_season": ["Aug-Jan"],
      "south_growing_season": ["Depends"],
      "germination_temp": "10-30",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "2-3",
      "sowing_distance_between_rows": "12",
      "days_to_maturation": "40-45",
      "link": "https://www.allthatgrows.in/products/radish-full-red"
    },
    {
      "name": "Spinach",
      "north_growing_season": ["Sept-Nov", "Feb"],
      "south_growing_season": ["Sept-Oct-Nov"],
      "germination_temp": "10-22",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "3",
      "sowing_distance_between_rows": "9",
      "days_to_maturation": "60",
      "link": "https://www.allthatgrows.in/products/spinach-all-green"
    },
    {
      "name": "Tomato",
      "north_growing_season": ["Jun-Aug", "Nov-Dec"],
      "south_growing_season": ["Jan-Feb", "Jun-Jul", "Oct-Nov"],
      "germination_temp": "20-30",
      "sowing_method": "Transplant",
      "sowing_depth": "0.25",
      "sowing_distance_between_seeds": "1",
      "sowing_distance_between_rows": "2.5",
      "days_to_maturation": "110-115",
      "link": "https://www.allthatgrows.in/products/cherry-tomato"
    },
    {
      "name": "Turnip",
      "north_growing_season": ["Oct-Nov"],
      "south_growing_season": ["Oct-Nov"],
      "germination_temp": "15-35",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "4",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "40-45",
      "link": "https://www.allthatgrows.in/products/turnip-desi-red"
    },
    {
      "name": "Turnip",
      "north_growing_season": ["Oct-Nov"],
      "south_growing_season": ["Oct-Nov"],
      "germination_temp": "15-35",
      "sowing_method": "Direct",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "4",
      "sowing_distance_between_rows": "1.5",
      "days_to_maturation": "40-45",
      "link": "https://www.allthatgrows.in/products/turnip-desi-red"
    },
    {
      "name": "Cauliflower",
      "north_growing_season": ["Mid-June"],
      "south_growing_season": ["Jun-Jul", "Aug-Sept"],
      "germination_temp": "<16",
      "sowing_method": "Transplant",
      "sowing_depth": "0.5",
      "sowing_distance_between_seeds": "2",
      "sowing_distance_between_rows": "2",
      "days_to_maturation": "120-125",
      "link": "https://www.allthatgrows.in/products/cauliflower"
    },
    {
      "name": "Potato",
      "north_growing_season": ["Oct-Dec"],
      "south_growing_season": ["Oct-Dec"],
      "germination_temp": "4",
      "sowing_method": "Direct",
      "sowing_depth": "4",
      "sowing_distance_between_seeds": "NA",
      "sowing_distance_between_rows": "12-18",
      "days_to_maturation": "70-120",
      "link": "NA"
    },
    {
      "name": "Pumpkin",
      "north_growing_season": ["Jan-Mar", "Sept-Dec", "May-Jun"],
      "south_growing_season": ["Jun-Jul", "Dec-Jan"],
      "germination_temp": "20-35",
      "sowing_method": "Direct",
      "sowing_depth": "1",
      "sowing_distance_between_seeds": "24-48",
      "sowing_distance_between_rows": "NA",
      "days_to_maturation": "70-75",
      "link": "https://www.allthatgrows.in/products/pumpkin-sadabahar"
    },
    {
      "name": "Corn",
      "north_growing_season": ["Oct-Nov"],
      "south_growing_season": ["Sept-Oct"],
      "germination_temp": "10",
      "sowing_method": "Direct",
      "sowing_depth": "1-1.5",
      "sowing_distance_between_seeds": "4-6",
      "sowing_distance_between_rows": "30-36",
      "days_to_maturation": "60-100",
      "link": "https://www.allthatgrows.in/products/yellow-corn-microgreens"
    },
    {
      "name": "Melon",
      "north_growing_season": ["Feb-Mar", "Jun-Jul"],
      "south_growing_season": ["Jan-Feb", "Mar-Jun", "Oct-Dec"],
      "germination_temp": "22-32",
      "sowing_method": "Direct",
      "sowing_depth": "1",
      "sowing_distance_between_seeds": "NA",
      "sowing_distance_between_rows": "18-24",
      "days_to_maturation": "70-85",
      "link": "https://www.allthatgrows.in/products/yellow-melon"
    },
  ];
}